steps:
  - label: "🔨 Build Go Application"
    key: "build"
    command: "cd hello && go build -o hello ."
    artifact_paths: "hello/hello"
    plugins:
      - docker#v5.8.0:
          image: "golang:1.18.0"
          workdir: /app
          volumes:
            - ".:/app"

  - block: "📝 Enter your name"
    key: "input"
    prompt: "What's your name?"
    fields:
      - text: "Name"
        key: "user-name"
        required: true

  - label: "🎉 Say Hello"
    command: |
      buildkite-agent artifact download "hello/hello" .
      chmod +x hello/hello
      USER_NAME=$(buildkite-agent meta-data get "user-name")
      ./hello/hello "$USER_NAME"
    depends_on: 
      - "build"
      - "input"
