steps:
  # Step 1: Build the Go application in Docker and upload artifact
  - label: "🔨 Build Go Application"
    key: "build"
    command: "cd hello && go build -o hello . && ls -la hello"
    artifact_paths: "hello/hello"
    plugins:
      - docker#v5.8.0:
          image: "golang:1.18.0"
          workdir: /app
          volumes:
            - ".:/app"

  # Step 2: Approval step after build
  - block: ":rocket: Are we ready?"
    key: "approval"
    depends_on: "build"

  # Step 3: Block step to get user input
  - block: "📝 Enter your name"
    key: "input"
    prompt: "What's your name?"
    fields:
      - text: "Code Name"
        key: "release-name"
        hint: "Enter your name here"
        required: true
    depends_on: "approval"

  # Step 4: Run the application script
  - label: "🎉 Say Hello"
    command: "./scripts.sh"
    depends_on: 
      - "build"
      - "input"
