steps:
  - label: "🔨 Build Go Application"
    key: "build"
    command: "cd hello && go build -o hello ."
    artifact_paths: "hello/hello"
    plugins:
      - docker#v5.8.0:
          image: "golang:1.18.0"
          workdir: /app
          volumes:
            - ".:/app"

  - block: "📝 Enter your name"
    key: "input"
    prompt: "What's your name?"
    fields:
      - text: "Name"
        key: "user-name"
        required: true

  - label: "🔍 Create Shell Script"
    key: "prepare"
    command: |
      cat > /tmp/run-app.sh << 'SCRIPT'
      #!/bin/bash
      buildkite-agent artifact download "hello/hello" .
      chmod +x hello/hello
      USER_NAME=$(buildkite-agent meta-data get user-name)
      ./hello/hello $USER_NAME
      SCRIPT
      chmod +x /tmp/run-app.sh
    depends_on: "input"

  - label: "🎉 Say Hello"
    command: "/tmp/run-app.sh"
    depends_on: 
      - "build"
      - "prepare"
